### ISSUE TITLE
Can you help me set this up?

### ISSUE THREAD

**Issue by htbrown** [MaxKorlaar/Pxl#12]
Hi.
I need help setting this up as I am a complete noob at doing things like this. I want to know how to attach it to my domain too.

**Comment by SunburntRock89** [comment]
install php composer then follow the guide in readme

**Comment by t5r7** [comment]
There's an installation guide [in the readme](https://github.com/MaxKorlaar/Pxl#a-short-guide-on-setting-it-up-server-side)

**Comment by billyprice1old** [comment]
Please Close this issue

**Comment by MaxKorlaar** [comment]
Hi. Due to university and work, I won't be able to assist in setting it up. However, it is built on top of Laravel which is immensely popular. I recommend you to read the Laravel documentation on how to set up a Laravel project if you can't get it to work.
