### ISSUE TITLE
Production / non-debug fatal errors to show errors/500 view

### ISSUE THREAD

**Issue by MaxKorlaar** [MaxKorlaar/Pxl#3]
They currently show the default error page, and without a stack trace (which it shows in debug mode) it is quite ugly and pointless to the end user.

It should, when not debugging, show views/errors/500.twig to the end user on a fatal exception. It already does this for HttpExceptions, but not for Twig exceptions for example.

**Comment by hugmanrique** [comment]
This docs page may be useful: https://laravel.com/docs/5.4/errors (especially the Exception Handler section)

**Comment by MaxKorlaar** [comment]
Fixed in #3933969a5ee0db5552536e8d719fdbeae712b13d, I have no idea how to link commits

**Comment by MaxKorlaar** [comment]
https://github.com/MaxKorlaar/Pxl/commit/3933969a5ee0db5552536e8d719fdbeae712b13d this D:
