### ISSUE TITLE
Register Form Design Flaw

### ISSUE THREAD

**Issue by samueldcs** [MaxKorlaar/Pxl#5]
So I've been messing around with Materialize for quite a long time and what I noticed in your code and in the version hosted at https://pxl-dev.maxkorlaar.nl was that the design is not properly responsive.

This is what happens: http://imgur.com/a/6cbiw
In my website, I also had this bug with small screens (like with my iPhone 5s)

I see what you did to make the center card, and I solved this is my code from taking alway `position: absolute;` from the `valign-wrapper`. (<a href="http://imgur.com/a/wkxST">before</a> and <a href="http://imgur.com/a/AGXnR">after</a>) I could not find where/if you did this, but I guess you did and that is my hint to fix. Thanks and hope you make it right.

**Comment by MaxKorlaar** [comment]
Fixed: https://i.maxkorlaar.de/SsY8zG

Thanks for reporting this issue 👍
