### ISSUE TITLE
Add 2fa requirement

### ISSUE THREAD

**Issue by MaxKorlaar** [MaxKorlaar/Pxl#6]
In the .env file there is a setting to make 2 factor auth mandatory for all users. The function has however not been implemented yet meaning that everyone can use the service without 2fa, even when they should have it enabled as configured.

I would like to prohibit uploading images when this setting is enabled and the current user does not have 2fa - Both when uploading via the API endpoint and via the website itself. I'd do it myself but considering it's Hacktoberfest 2017 I thought that it'd be nice to give someone else the chance to make this small change.

**Comment by Roonschot** [comment]
is goed
:ctfu:
